version: "1"
name: ai_content_chain
description: "Orchestrate AI agents to generate, analyze, and improve content"
enabled: true

inputs:
  - name: topic
    type: string
    required: true
    description: "The topic for the press release"

triggers:
  - type: manual
    enabled: true

steps:
  - name: draft_content
    type: kibana.post_agent_builder_converse
    with:
      agent_id: agent_content_creator
      input: "Write a short, 1-2 sentence press release about this topic: {{ inputs.topic }}"

  - name: first_check
    type: kibana.post_agent_builder_converse
    with:
      agent_id: agent_sentiment_analyzer
      input: "{{ steps.draft_content.output.response.message }}"

  - name: remediation_spin
    type: kibana.post_agent_builder_converse
    with:
      agent_id: agent_pr_spin_specialist
      input: |
        The following draft was written:
        "{{ steps.draft_content.output.response.message }}"
        
        It was analyzed with this sentiment:
        "{{ steps.first_check.output.response.message.sentiment }}"
        
        Please revise this draft to have a strongly positive spin.

  - name: final_check
    type: kibana.post_agent_builder_converse
    with:
      agent_id: agent_sentiment_analyzer
      input: "{{ steps.remediation_spin.output.response.message }}"

  - name: final_report
    type: console
    with:
      message: |
        ---
        Original Draft: {{ steps.draft_content.output.response.message }}
        Original Sentiment: {{ steps.first_check.output.response.message.sentiment }}
        ---
        Revised Draft: {{ steps.remediation_spin.output.response.message }}
        Final Sentiment: {{ steps.final_check.output.response.message.sentiment }}
        ---
        
        {% if steps.final_check.output.response.message.sentiment == "POSITIVE" %}
        ✅ Content is approved and ready to send.
        {% else %}
        ❌ FAILED: Content still has negative sentiment after remediation.
        {% endif %}

